test = {   'name': 'q34',
    'points': 3,
    'suites': [   {   'cases': [   {'code': ">>> 'a' in y34\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> 'b' in y34\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> 'c' in y34\nTrue", 'hidden': True, 'locked': False},
                                   {'code': ">>> 'd' in y34\nTrue", 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
